# Generated by Django 5.2.17 on 2026-08-26 13:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheatreProject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('user_prompt', models.TextField()),
                ('language', models.CharField(default='bn', max_length=16)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('theme', models.CharField(blank=True, max_length=255)),
                ('actor_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stage_size', models.CharField(blank=True, max_length=100)),
                ('available_lights', models.JSONField(blank=True, default=list, help_text='JSON list of fixture names or fixture specifications.')),
                ('generated_json', models.JSONField(blank=True, default=dict, help_text='Latest fully validated production JSON; never store unsafe output here.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='theatre_proj_created_idx'), models.Index(fields=['language', 'genre'], name='theatre_proj_lang_gen_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_count__gte', 1)), name='theatre_project_actor_count_gte_1'), models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1)), name='theatre_project_duration_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('scene_sources', models.JSONField(blank=True, default=list, help_text='Ordered scene source IDs used for this run.')),
                ('blocking_sources', models.JSONField(blank=True, default=list, help_text='Ordered blocking source IDs used for this run.')),
                ('lighting_sources', models.JSONField(blank=True, default=list, help_text='Ordered lighting source IDs used for this run.')),
                ('retrieval_trace', models.JSONField(blank=True, default=list, help_text='Ranks, similarity scores, source IDs, and view types for reproducibility.')),
                ('raw_output', models.TextField(blank=True)),
                ('validated', models.BooleanField(db_index=True, default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('generation_time_seconds', models.FloatField(help_text='End-to-end generation duration in seconds.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='theatre.theatreproject')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['project', 'created_at'], name='theatre_run_proj_time_idx'), models.Index(fields=['model_name'], name='theatre_run_model_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('generation_time_seconds__gte', 0)), name='theatre_run_generation_time_gte_0')],
            },
        ),
    ]
