# Generated by Django 5.2.17 on 2026-08-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='research_query',
            field=models.TextField(blank=True, help_text='Exact researcher query used for this run, when applicable.'),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='retrieval_config',
            field=models.JSONField(blank=True, default=dict, help_text='Selected per-view Top-K configuration for reproducibility.'),
        ),
    ]
