# Generated by Django 5.2.17 on 2026-08-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_generationrun_research_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='rag_mode',
            field=models.CharField(choices=[('no_rag', 'Mode 1 — No RAG'), ('scene_only', 'Mode 2 — Scene-only RAG'), ('scene_blocking', 'Mode 3 — Scene + Blocking RAG'), ('scene_lighting', 'Mode 4 — Scene + Lighting RAG'), ('single_combined', 'Mode 5 — Single combined retrieval RAG'), ('full_multiview', 'Mode 6 — Full Multi-View RAG')], db_index=True, default='full_multiview', help_text='Retrieval ablation mode used for this generation run.', max_length=32),
        ),
    ]
