# Generated by Django 5.2.17 on 2026-08-26 18:06

from django.db import migrations, models


def backfill_unambiguous_run_snapshots(apps, schema_editor):
    """Copy project JSON only when exactly one run can own that snapshot."""
    TheatreProject = apps.get_model("theatre", "TheatreProject")
    for project in TheatreProject.objects.exclude(generated_json={}):
        runs = list(project.generation_runs.all()[:2])
        if len(runs) == 1 and runs[0].validated:
            runs[0].generated_json = project.generated_json
            runs[0].save(update_fields=("generated_json",))


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_generationrun_rag_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='generated_json',
            field=models.JSONField(blank=True, default=dict, help_text='Validated production snapshot for this specific run.'),
        ),
        migrations.RunPython(
            backfill_unambiguous_run_snapshots,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
