# Generated by Django 5.2.17 on 2026-08-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_generationrun_generated_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='model_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Allowlisted non-secret model settings used for this run.'),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='repair_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of structured validation-repair requests made.'),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='user_input',
            field=models.TextField(blank=True, help_text='Immutable user theatre requirements snapshot for reproducibility.'),
        ),
    ]
